services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    container_name: backend_container
    networks:
      - mern

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: frontend_container
    networks:
      - mern

networks:
  mern:
    driver: bridge
